export const text = {
	menu: {
		prompt: ['- CLICK TO START -', '- CLICK PARA EMPEZAR -', '- 点击开始 -'],
		loading: ['Loading...', 'Cargando...', '加载中...'],
		button: {
			play: ['Play', 'Jugar', '继续游戏'],
			tutorial: ['Tutorial', 'Tutorial', '教程'],
			settings: ['Settings', 'Opciones', '设置'],
			credits: ['Credits', 'Créditos', '制作人员'],
			exit: ['Exit', 'Salir', '退出'],
			newGame: ['New game', 'Nueva partida', '新游戏'],
		},
		newGame: {
			section: {
				characterCreation: ['Character creation', 'Creación de personaje', '创建角色'],
			},
			name: ['Name', 'Nombre', '姓名'],
			sprite: ['Sprite', 'Apariencia', '外观'],
			starter: ['Partner', 'Compañero', '搭档'],
			button: ['Start new game', 'Empezar nueva partida', '开始新游戏'],
		},
		settings: {
			section: {
				language: ['Language', 'Idioma', '语言'],
				game: ['Game', 'Juego', '游戏'],
				view: ['View', 'Pantalla', '显示'],
				audio: ['Audio', 'Volumen', '音频'],
				data: ['Data', 'Datos', '数据'],
			},
			language: {
				0: ['Language', 'Idioma', '语言'],
			}, 
			game: {
				0: ['Capture Window', 'Vent. Captura', '捕捉窗口'],
				1: ['Auto Lvl Up', 'Auto Leveo', '自动升级'],
			},
			view: {
				0: ['Scale', 'Escala', '缩放'],
				1: ['Border', 'Borde', '边框'],
				2: ['Palette', 'Paleta', '调色板'],
			},
			audio: {
				0: ['Master', 'General', '主音量'],
				1: ['Music', 'Música', '音乐'],
				2: ['Interface', 'Interfaz', '界面'],
				3: ['Effects', 'Efectos', '音效'],
			},
			data: {
				0: ['Delete save data', 'Borrar datos de guardado', '删除存档'],
				1: ['You sure?', '¿Seguro?', '确定吗？'],
				2: ['But are you sure?', '¿Pero seguro?', '真的确定吗？'],
				3: ['Click and data will be deleted', 'Si pulsas se borrarán tus datos', '点击后数据将被删除'],
			}
		},
		tutorial: {
			name: {
				0: ['POINT & CLICK', 'POINT & CLICK', '点击操作'],
				1: ['MENU', 'MENÚ', '菜单'],
				2: ['AUTO-BATTLE', 'AUTOCOMBATE', '自动战斗'],
				3: ['LEVEL UP', 'SUBE DE NIVEL', '升级'],
				4: ['RECRUIT POKÉMON', 'RECLUTA POKÉMON', '招募宝可梦'],
				5: ['LEVEL CAP', 'LÍMITE DE NIVEL', '等级上限'],
				6: ['SHOPS', 'TIENDAS', '商店'],
				7: ['GYM LEADERS', 'LÍDERES DE GIMNASIO', '道馆馆主'],
				8: ['EVOLVE', 'EVOLUCIONA', '进化'],
				9: ['LEARN MOVES', 'APRENDE MOVIMIENTOS', '学习招式'],
				10: ['FORGET MOVES', 'OLVIDA MOVIMIENTOS', '遗忘招式'],
				11: ['POWER UP YOUR TEAM', 'POTENCIA TU EQUIPO', '强化队伍'], 
				12: ['EXPLORE THE WORLD', 'EXPLORA EL MUNDO', '探索世界'],
			},
			description: {
				0: ['Interact with the world using only the mouse.', 'Interactúa con el mundo únicamente con el ratón.', '仅使用鼠标与世界互动。'],
				1: ['Open the menu with the ESC key.', 'Abre el menú con la tecla ESC.', '按 ESC 键打开菜单。'],
				2: ['Battles are automatic: choose your Pokémon and move to defeat your foes.', 'Los combates son automáticos: elige tu Pokémon y su movimiento para derrotar a los rivales.', '战斗是自动的：选择宝可梦和招式来击败对手。'],
				3: ['When your EXP bar is full, level up from Menu → Team.', 'Cuando tu barra de experiencia llegue al máximo, sube de nivel desde Menú → Equipo.', '经验条满后，从菜单 → 队伍中升级。'],
				4: ['Defeat wild Pokémon so they can join your team.', 'Los Pokémon salvajes podrán unirse a tu equipo cuando los derrotes.', '击败野生宝可梦后，它们可能会加入你的队伍。'],
				5: ['Your Pokémon\u2019s max level depends on your gym badges.', 'El nivel máximo de tus Pokémon está limitado por tus medallas de gimnasio y no podrás sobrepasarlo.', '宝可梦的最高等级取决于你拥有的道馆徽章数量。'],
				6: ['Visit the shops in each city. Highlighted items are marked in red!', 'Visita las tiendas de cada ciudad. ¡En cada una encontrarás objetos destacados marcados en rojo!', '访问每个城市的商店。推荐物品标为红色！'],
				7: ['Earn badges to progress, raise your level cap, and unlock more shop items.', 'Gana medallas para avanzar en tu aventura, aumentar el límite de nivel y desbloquear más objetos en las tiendas.', '获得徽章来推进冒险，提升等级上限，解锁更多商店物品。'],
				8: ['When a Pokémon meets the requirements, evolve it in the Evolution Dojo.', 'Cuando un Pokémon cumpla los requisitos, evolucionalo en el Dojo de Evolución.', '满足条件后，在进化道场进化宝可梦。'],
				9: ['Teach new moves to make your Pokémon more versatile.', 'Enseña nuevos movimientos a tus Pokémon para que sean más versátiles.', '教授新招式让宝可梦更加全面。'],
				10: ['Forget moves with the Move Deleter to make room for stronger ones.', 'Olvida movimientos con el tutor Quita-movimientos para hacer hueco a movimientos más potentes.', '通过遗忘招式导师遗忘招式，为更强招式腾出空间。'],
				11: ['Use vitamins and herbs to strengthen your Pokémon.', 'Usa vitaminas y hierbas para fortalecer a tus Pokémon.', '使用维生素和草药来强化宝可梦。'],
				12: ['Quests and secrets await in Johto, Kanto, and who knows where else!', '¡Misiones y secretos te esperan en Johto, Kanto y, quién sabe, en muchos otros lugares!', '城都、关都以及更多地方的冒险与秘密等待着你！'],
			}
		},
		credits: {
			section: {
				developer: ['Developer', 'Programación', '开发者'],
				disclaimer: ['Disclaimer', 'Disclaimer', '免责声明'],
				testers: ['Testers', 'Testers', '测试人员'],
				assets: ['Assets', 'Assets', '素材'],
			},
		},
	},
	gameMenu: {
		pokedex: ['Pokédex', 'Pokédex', '宝可梦图鉴'],
		team: ['Team', 'Equipo', '队伍'],
		bag: ['Bag', 'Mochila', '背包'],
		player: ['Profile', 'Perfil', '训练师档案'],
		map: ['Map', 'Mapa', '地图'],
		save: ['Save', 'Guardar', '保存'],
		achievements: ['Achievements', 'Logros', '成就'],
		settings: ['Settings', 'Opciones', '设置'],
		close: ['Close', 'Cerrar', '关闭'],
		exit: ['Exit', 'Salir', '退出'],
		hints: {
			default: ["Select an option from the menu.", "Selecciona una opción del menú.", "从菜单中选择一个选项。"],
			pokedex: ["Check the Pokémon you have seen and caught.", "Consulta los Pokémon que has visto y atrapado.", "查看你已经见过和捕捉的宝可梦。"],
			team: ["View your current Pokémon team.", "Revisa tu equipo Pokémon actual.", "查看你当前的宝可梦队伍。"],
			bag: ["Open your bag to see your items.", "Abre la mochila para ver tus objetos.", "打开背包查看你的道具。"],
			player: ["View your trainer profile and stats.", "Muestra tu tarjeta de entrenador.", "查看你的训练师档案和统计。"],
			map: ["Open the world map.", "Muestra el mapa de la región.", "打开世界地图。"],
			settings: ["Adjust game settings.", "Ajusta configuraciones del juego.", "调整游戏设置。"],
			achievements: ["View your completed challenges.", "Consulta tus desafíos completados.", "查看你已完成的挑战。"],
			save: ["Save your current game progress.", "Guarda tu partida actual.", "保存当前游戏进度。"],
			close: ["Close the menu and return to the game.", "Cierra el menú y vuelve al juego.", "关闭菜单返回游戏。"],
			exit: ["Exit to the main menu.", "Sal al menú principal del juego.", "退出到主菜单。"]	
		},
		menuPlayer: {
			gold: ["Money", "Dinero", "金钱"],
			pokedex: ["Pokédex", "Pokédex", "图鉴"],
			badges: ["Badges", "Medallas", "徽章"],
			start: ["Started", "Inicio", "开始时间"],
			time: ["Time", "Tiempo", "游戏时间"],
		},
		exitConfirm: ['Exit without save?', '¿Salir sin guardar?', '不保存就退出吗？'],
	},
	stats: {
		hp: ['Hp', 'Ps', 'HP'], 
		atk: ['Attack', 'Ataque', '攻击'], 
		def: ['Defense', 'Defensa', '防御'], 
		spa: ['Sp. Atk', 'At. Esp.', '特攻'], 
		spd: ['Sp. Def', 'Def. Esp.', '特防'], 
		spe: ['Speed', 'Velocidad', '速度'],
		nature: ['Nature', 'Naturaleza', '性格'],
		ability: ['Ability', 'Habilidad', '特性'],
		move: ['Move', 'Movimiento', '招式'],
		moves: ['Moves', 'Movimientos', '招式'],
		item: ['Item', 'Objeto', '道具'],
		level: ['Level', 'Nivel', '等级'],
		levelButton: ['Lvl. Up', '+ Nivel', '升级'],
		short: {
			level: ['Lv.', 'Nv.', 'Lv.'],
			hp: ['Hp', 'Ps', 'HP'], 
			atk: ['Atk', 'Atq', '攻击'], 
			def: ['Def', 'Def', '防御'], 
			spa: ['Spa', 'AtE', '特攻'], 
			spd: ['Spd', 'DfE', '特防'], 
			spe: ['Spe', 'Vel', '速度'],
		}
	},
	pokeCenter: {
		heal: ['Heal team', 'Curar equipo', '治疗队伍'],
		box: ['Pokémon storage', 'Caja pokémon', '宝可梦仓库'],
		unionRoom: ['Union room', 'Sala unión', '联合房间'],
		description: {
			default: ['Welcome to the Pokémon Center!', '¡Bienvenido al Centro Pokémon!', '欢迎来到宝可梦中心！'],
			heal: ['Restore your team\u2019s full health and refill potions.', 'Restaurar la salud completa a tu equipo pokémon y rellena las pociones.', '恢复队伍全部生命值并补充药剂。'],
			box: ['Go to Pokémon Storage. <br>You can swap Pokémon in your team here', 'Ir al Almacenamiento Pokémon. <br>Aquí podrás cambiar los Pokémon de tu equipo.', '前往宝可梦仓库。<br>在这里可以更换队伍中的宝可梦。'],
			unionRoom: ['Enter the Union Room. <br>You can redeem your Union Tickets here.', 'Entrar en la Sala Unión. <br>Aquí podrás canjear tus Tickets Unión.', '进入联合房间。<br>在这里可以兑换联合券。'],
		},
		storage: {
			add: ['Add to team', 'Añadir al equipo', '加入队伍'],
			remove: ['Remove from team', 'Retirar del equipo', '从队伍移出'],
			release: ['Release', 'Liberar', '放生'],
			n: ['#num', '#num', '#编号'],
			name: ['Aa-Zz', 'Aa-Zz', '名称'],
			lvl: ['Lvl', 'Nvl', '等级'],
			type: ['Type', 'Tipo', '属性'],
			shiny: ['Shiny', 'Shiny', '闪光'],
		},
		tickets: {
			strong: ['Superstrong pokémon', 'Pokémon superfuerte', '超强宝可梦'],
			transmuted: ['Transmuted pokémon', 'Pokémon alterado', '变异宝可梦'],
			shiny: ['Shiny pokémon', 'Pokémon variocolor', '闪光宝可梦'],
			description: {
				strong: ['', 'Obtén un pokémon aleatorio con altos IV.', '随机获得一只高个体值宝可梦。'],
				transmuted: ['', 'Obtén un pokémon aleatorio con tipos y movimientos aleatorios', '随机获得一只属性和招式随机的宝可梦。'],
				shiny: ['', 'Obtén un pokémon aleatorio variocolor', '随机获得一只闪光宝可梦。'],
			},
			prompt: ['Returns are not accepted!','¡No se aceptan devoluciones!', '恕不退换！']
		}
	},
	pokeMart: {
		buy: ['Purchase', 'Comprar', '购买'],
		localProduct: ['Local product', 'Prod. locales', '本地特产'],
		sell: ['Sell', 'Vender', '出售'],
		description: {
			default: ['Welcome to the PokéMart!', '¡Bienvenido a la Tienda Pokémon!', '欢迎来到友好商店！'],
			buy: ['Buy supplies for your adventure.', 'Compra suministros para tu aventura.', '为冒险购买补给品。'],
			localProduct: ['Check out our local products', 'Echa un ojo a los productos locales.', '看看我们的本地特产。'],
			sell: ['Sell the items you no longer need.', 'Vende los objetos que ya no te hagan falta.', '出售你不再需要的道具。'],
		},
		tokens: ['tokens', 'fichas', '代币'],
		tokensShort: ['tkns', 'fichas', '代币'],
	},
	casino: {
		play: ['Play', 'Jugar', '开始'],
		betSelection: ['Bet selection', 'Selecciona una apuesta', '选择下注'],
		notEnoughTokens: ["You don't have enough tokens.", 'No cuentas con suficientes fichas.', '你没有足够的代币。'],
		bet: ['Bet', 'Apuesta', '下注'],
		spin: ['Spin', 'Girar', '旋转'],
		latestResults: ['Latest results', 'Resultados anteriores', '最近结果'],
		game: {
			blackjack: ['Blackjack', 'Blackjack', '二十一点'],
			roulette: ['Roulette', 'Ruleta', '轮盘'],
			voltorb: ['Voltorbflip', 'Giravoltorb', '翻雷电球'],
			slot: ['Slots', 'Tragaperras', '老虎机'],
		},
		blackjack: {
			hit: ['Hit', 'Pedir', '要牌'],
			stand: ['Stand', 'Plantarse', '停牌'],
			leave: ['Leave', 'Irse', '离开'],
			rematch: ['Rematch', 'Otra', '再来'],
			win: ['You win!', '¡Has ganado!', '你赢了！'],
			draw: ['Draw!', '¡Empate!', '平局！'],
			lose: ['You lost!', '¡Derrota!', '你输了！'],
			dealer: ['Dealer', 'Dealer', '庄家'],
			lostTokens: ['+0 fichas', '+0 fichas', '+0 代币'],
			notEnoughTokensContinue: ["You don't have enough tokens to continue playing.", 'No tienes suficientes fichas para seguir jugando.', '你没有足够的代币继续游戏。'],
		}
	},
	misc: {
		accept: ['Accept', 'Aceptar', '确认'],
		cancel: ['Cancel', 'Cancelar', '取消'],
		evolve: ['Evolve', 'Evolucionar', '进化'],
		unlearn: ['Unlearn', 'Olvidar', '遗忘'],
		back: ['Back', 'Volver', '返回'],
		unlearned: ['unlearned', 'no aprendido', '未学会'],
		amount: ['Amount', 'Cantidad', '数量'],
		item: ['Item', 'Objeto', '道具'],
		all: ['All', 'Todo', '全部'],
		consumable: ['Consumables', 'Consumibles', '消耗品'],
		battle: ['Battle', 'Combate', '战斗'],
		key: ['Key', 'Clave', '关键'],
		resource: ['Resources', 'Recursos', '资源'],
		tm: ['TM', 'MT', '招式机'],
		time: ['Time', 'Horario', '时间'],
		cost: ['Cost', 'Coste', '费用'],
		dawn: ['Dawn', 'Madrugada', '黎明'],
		morning: ['Morning', 'Mañana', '早晨'],
		day: ['Daytime', 'Día', '白天'],
		night: ['Nighttime', 'Noche', '夜晚'],
		use: ['Use', 'Usar', '使用'],
		type: ['Type', 'Tipo', '属性'],
		category: ['Class', 'Clase', '类别'],
		power: ['Power', 'Poder', '威力'],
		physical: ['Physical', 'Físico', '物理'],
		special: ['Special', 'Especial', '特殊'],
		able: ['Able', 'Apto', '可用'],
		notAble: ['Not able', 'No apto', '不可用'],	
		noSpace: ['No space', 'Sin espacio', '空间不足'],
		learned: ['Learned', 'Aprendido', '已学会'],
		gc: ['GC!', '¡GC!', 'GC!'],
		progress: ['Progress', 'Progreso', '进度'],
		record: ['Record', 'Récord', '记录'],
		achievement: ['New achievement!', '¡Nuevo logro!', '新成就！'],
		keyItem: ['Key item', 'Objeto clave', '关键道具'],
		evolutionItem: ['Evolution item', 'Objeto evolutivo', '进化道具'],
		tickets: ['Tickets', 'Tickets', '联合券'],
		or: ['or', 'o', '或'],
	},
	moveDeleter: {
		error: ['The Pokémon cannot forget a move if it is the only one it knows', 'El Pokémon no puede olvidar un movimiento si es el único que conoce', '宝可梦不能遗忘唯一的招式'],
		cost: ['Forgetting a move costs $100', 'Olvidar un movimiento tiene un precio de $100', '遗忘招式花费 $100']
	},
	gym: {
		ready: ['Ready', 'Listo', '准备'],
		winPrompt: ['You have beaten this gym!', '¡Has derrotado este gimnasio!', '你已经击败了这个道馆！'],
	},
	route: {
		captureModeOn: ['CAPTURE MODE on', 'MODO CAPTURA activado', '捕捉模式：开启'],
		captureModeShiny: ['CAPTURE MODE only shiny', 'MODO CAPTURA solo variocolor', '捕捉模式：仅闪光'],
		captureModeOff: ['CAPTURE MODE off', 'MODO CAPTURA desactivado', '捕捉模式：关闭'],
		capturePrompt: ['Do you want this Pokémon to join your party?', '¿Quieres que este Pokémon se una a tu grupo?', '要让这只宝可梦加入队伍吗？'],
		capturePromptBottom: ['If you have 6 Pokémon in your party, they will be sent to the Pokémon Center Box.', 
								'Si tienes 6 Pokémon en el grupo, se enviará a la Caja del Centro Pokémon',
								'如果队伍已有6只宝可梦，它将被传送到宝可梦中心的仓库。'],
		expShareModeOn: ['EXP SHARE on', 'REPARTIR EXP activado', '经验分享：开启'],
		expShareModeOff: ['EXP SHARE off', 'REPARTIR EXP desactivado', '经验分享：关闭'],
		defeatedPrompt:  ['All your Pokémon have been defeated.', 'Todos tus Pokémon han sido derrotados.', '你的宝可梦全部倒下了。'],
		defeatedPromptBottom:  ['You will return to the last Pokémon Center where you rested.', 'Volverás al último Centro Pokémon en el cual descansaste.', '你将回到上次休息的宝可梦中心。'],
		travel: ['Travel', 'Viajar', '旅行'],
		radarOn: ['POkÉ RADAR on', 'POkÉRADAR activado', '宝可雷达：开启'],
		radarOff: ['POkÉ RADAR off', 'POkÉRADAR desactivado', '宝可雷达：关闭'],
		autobattleOn: ['Auto changes on', 'Cambios automáticos activados', '自动换人：开启'],
		autobattleOff: ['Auto changes off', 'Cambios automáticos desactivados', '自动换人：关闭'],
		statusOn: ['ON', 'ON', '开'],
		statusOff: ['OFF', 'OFF', '关'],
		statusShiny: ['SHINY', 'SHINY', '闪光'],
		statusSlowed: ['SLOWED', 'SLOWED', '减速'],
		statusStuned: ['STUNED', 'STUNED', '眩晕'],
		statusFlinched: ['FLINCHED', 'FLINCHED', '畏缩'],
		regionJohto: ['JOHTO', 'JOHTO', '城都'],
		regionKanto: ['KANTO', 'KANTO', '关都'],
		regionApachan: ['APACHÁN', 'APACHÁN', '阿帕查'],
		hallOfFame: ['Hall of Fame', 'Hall of Fame', '名人堂'],
		push: ['PUSH', 'PUSH', '按下'],
		max: ['MAX', 'MAX', '最大'],
		victory: ['VICTORY ', 'VICTORIA ', '胜利！'],
		streak: ['Actual streak: ', 'Racha actual: ', '当前连胜：'],
		newRecord: ['New Record!', '¡Nuevo Récord!', '新纪录！'],
		defeated: [' defeated!', ' derrotado!', ' 被击败了！'],
		earned: ['You have earned $', 'Has obtenido $', '你获得了 $'],
		maxLevel: ['Max level: ', 'Nivel máximo aumentado: ', '最大等级：'],
		shopMore: ['Shops will sell more items.', '¡Hay nuevos objetos en las tiendas!', '商店将出售更多商品。'],
		goldUnit: ['g', 'g', '金币'],
		close: ['X', 'X', 'X'],
	},
	egg: {
		name: ['Egg', 'Huevo', '蛋'],
		desc: ["Wonder what's inside?", '¿Qué habrá dentro?', '里面会是什么呢？'],
		0: ['This Egg needs a lot more time to hatch.', "Parece que a este huevo le va a costar mucho abrirse.", '这个蛋还需要很长时间才能孵化。'],
		1: ["It needs more time, though.", "Tendrás que esperar un poco más.", '不过还需要更多时间。'],
		2: ['It moves around inside sometimes. \nIt must be close to hatching.', "A veces se mueve. \nDebe estar a punto de salir.", '它偶尔会动一下。\n应该快孵化了。'],
		3: ["It's making sounds inside. \nIt's going to hatch soon!", "Se escuchan sonidos. \n¡Pronto saldrá!", '里面有声音传出来。\n马上就要孵化了！'],
		hatch: ['Hatch', 'Eclosionar', '孵化'],
		hatched: ['A new Pokémon has hatched!', '¡Un nuevo Pokémon ha salido del huevo!', '新的宝可梦孵化了！']
	}
}

export function formatNumberWithCommas(num) {
    return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}